version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: multimedios_rabbitmq
    ports:
      - "5672:5672"   # Puerto AMQP para conexiones
      - "15672:15672" # Dashboard Web de Administración
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  producer:
    build: .
    container_name: multimedios_producer
    command: uvicorn producer:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      rabbitmq:
        condition: service_healthy

  worker:
    build: .
    container_name: multimedios_worker
    command: python worker.py
    volumes:
      - .:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
